export const URLS = {
  ZITI_DASHBOARD: '/ziti-dashboard',
  ZITI_IDENTITIES: '/ziti-identities',
  ZITI_JWT_SIGNERS: '/ziti-jwt-signers',
  ZITI_SERVICES: '/ziti-services',
  ZITI_ROUTERS: '/ziti-routers',
  ZITI_TRANSIT_ROUTERS: '/ziti-transit-routers',
  ZITI_CONFIGS: '/ziti-configs',
  ZITI_CONFIG_TYPES: '/ziti-config-types',
  ZITI_RECIPES: '/ziti-recipes',
  ZITI_TERMINATORS: '/ziti-terminators',
  ZITI_AUTH_POLICIES: '/ziti-auth-policies',
  ZITI_SERVICE_POLICIES: '/ziti-service-policies',
  ZITI_ROUTER_POLICIES: '/ziti-router-policies',
  ZITI_SERVICE_ROUTER_POLICIES: '/ziti-service-router-policies',
  ZITI_POSTURE_CHECKS: '/ziti-posture-checks',
  ZITI_CERT_AUTHORITIES: '/ziti-certificate-authorities',
  ZITI_SESSIONS: '/ziti-sessions',
  ZITI_LOGIN: '/ziti-login',
  ZITI_ORGANIZATION: '/ziti-organization',
  ZITI_PROFILE: '/ziti-profile',
  ZITI_SERVERS: '/ziti-servers',
  ZITI_SETTINGS: '/ziti-settings',
  ZAC_LOGIN: '/ziti-login'
};
